### ISSUE TITLE
inventory system

### ISSUE THREAD

**Issue by chilinrakkoon** [AsjadIqbal/InventoryManagementSystem#1]
i am having trouble login in i have change the root name and password as you instructed i don't know what i am doing wrong please help me

**Comment by AsjadIqbal** [comment]
Hi, can you please describe the issue in more detail? Have you imported the schema onto your local machine?

**Comment by chilinrakkoon** [comment]
hi thank you for responding i fanily fegured it out , it works now i was making a mistake on the credetial code

**Comment by chilinrakkoon** [comment]
one more question could you nake the app a web application

**Comment by AsjadIqbal** [comment]
> one more question could you nake the app a web application
> 
> 

Yes making it into a web application using Spring was going to be my next move but I suppose I'll be working on something entirely new.
